services:

  zabbix_db:
    image: zukidocker/oss:zbx5db
    container_name: zbx5db_psql14
    ports:  
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    volumes:
      - ./pg_confs/postgresql.conf:/etc/postgresql.conf
    environment:
      POSTGRES_PASSWORD: zabbix

  zabbix_server:
      image: zabbix/zabbix-server-pgsql:5.0-alpine-latest
      container_name: zabbix_server_psql
      ports:  
        - "10051:10051"
      environment:
        DB_SERVER_HOST: zabbix_db
        MYSQL_USER: "zabbix"
        MYSQL_PASSWORD: "zabbix"
  
  zabbix_web_apache:
    image: zabbix/zabbix-web-apache-pgsql:5.0-alpine-latest
    container_name: zabbix_web_apache_psql
    ports:  
      - "8080:8080"
    environment:
      DB_SERVER_HOST: zabbix_db
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      ZBX_SERVER_HOST: zabbix_server
      PHP_TZ: "Asia/Yangon"
