version: '3'

services:

  zabbix_db:
    image: oss:psql
    container_name: psql14
    ports:  
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: zabbix

  zabbix_server:
      image: zabbix/zabbix-server-pgsql:alpine-6.0-latest
      container_name: zabbix_server
      ports:  
        - "10051:10051"
      environment:
        DB_SERVER_HOST: "192.168.50.95"
        MYSQL_USER: "zabbix"
        MYSQL_PASSWORD: "zabbix"
  
  zabbix_web_apache:
    image: zabbix/zabbix-server-pgsql:alpine-6.0-latest
    container_name: zabbix_web_apache
    ports:  
      - "80:8080"
    environment:
      DB_SERVER_HOST: "192.168.50.95"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      ZBX_SERVER_HOST: "192.168.50.95"
      PHP_TZ: "Asia/Yangon"