services:

  zabbix_db:
    image: zukidocker/oss:zbx6db_psql
    container_name: psql14
    ports:  
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: zabbix

  zabbix_server:
      image: zabbix/zabbix-server-pgsql:alpine-6.0-latest
      container_name: zabbix_server_psql
      ports:  
        - "10051:10051"
      environment:
        DB_SERVER_HOST: zabbix_db
        MYSQL_USER: "zabbix"
        MYSQL_PASSWORD: "zabbix"
  
  zabbix_web_apache:
    image: zabbix/zabbix-web-apache-pgsql:alpine-6.0-latest
    container_name: zabbix_web_apache_psql
    ports:  
      - "8080:8080"
    environment:
      DB_SERVER_HOST: zabbix_db
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      ZBX_SERVER_HOST: zabbix_server
      PHP_TZ: "Asia/Yangon"
