services:

  zabbix_db:
    image: zukidocker/oss:zbx5db_mysql
    container_name: zbx5db
    ports:  
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: zabbix

  zabbix_server:
    image: zabbix/zabbix-server-mysql:5.0-alpine-latest
    container_name: zabbix_server_mysql
    ports:  
      - "10051:10051"
    environment:
      DB_SERVER_HOST: zabbix_db
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
  
  zabbix_web_apache:
    image: zabbix/zabbix-web-apache-mysql:5.0-alpine-latest
    container_name: zabbix_web_apache_mysql
    ports:  
      - "8080:8080"
    environment:
      DB_SERVER_HOST: zabbix_db
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      ZBX_SERVER_HOST: zabbix_server
      PHP_TZ: "Asia/Yangon"

  
